version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=senao
    ports:
      - "5432:5432"
    networks: 
      - senao-network
  api:
    image: amboseqiu/senao_hw
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: [ "/app/main" ]
    networks: 
      - senao-network
networks:
  senao-network:
    name: senao-network