definitions:
  model.AccountRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.DocResponseAccountNotFound:
    properties:
      reason:
        example: Login account not found
        type: string
      success:
        example: false
        type: boolean
    type: object
  model.DocResponseAlreadyExisted:
    properties:
      reason:
        example: Account is already existed
        type: string
      success:
        example: false
        type: boolean
    type: object
  model.DocResponseBadRequest:
    properties:
      reason:
        example: Password is too short
        type: string
      success:
        example: false
        type: boolean
    type: object
  model.DocResponseSuccess:
    properties:
      reason:
        example: ""
        type: string
      success:
        example: true
        type: boolean
    type: object
  model.DocResponseTooManyRequest:
    properties:
      reason:
        example: too many failed login attempt, please try it later
        type: string
      success:
        example: false
        type: boolean
    type: object
  model.DocResponseWrongPassword:
    properties:
      reason:
        example: Wrong password
        type: string
      success:
        example: false
        type: boolean
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  termsOfService: http://swagger.io/terms/
paths:
  /accounts:
    post:
      description: |-
        Create account by username and password
        Note:
        username: a string representing the desired username for the account, with a minimum length of 3 characters and a maximum length of 32 characters.
        password: a string representing the desired password for the account, with a minimum length of 8 characters and a maximum length of 32 characters,
        containing at least 1 uppercase letter, 1 lowercase letter, and 1 number.
      parameters:
      - description: Account Request Struct
        in: body
        name: accountRequest
        required: true
        schema:
          $ref: '#/definitions/model.AccountRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.DocResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.DocResponseBadRequest'
        "409":
          description: Account Is Already Existed
          schema:
            $ref: '#/definitions/model.DocResponseAlreadyExisted'
      summary: Create an account
      tags:
      - accounts
  /login:
    post:
      consumes:
      - application/json
      description: |-
        Login account and verify username and password
        Note:
        If the password verification fails five times, the user should wait one minute before attempting to verify the password again.
      parameters:
      - description: Account Request Struct
        in: body
        name: accountRequest
        required: true
        schema:
          $ref: '#/definitions/model.AccountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.DocResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.DocResponseAccountNotFound'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.DocResponseWrongPassword'
        "429":
          description: Too Many Failed Login Attempts
          schema:
            $ref: '#/definitions/model.DocResponseTooManyRequest'
      summary: Login account
      tags:
      - accounts
swagger: "2.0"
